// flow-typed signature: e777a2faeb78dd90167553603abb1f36
// flow-typed version: <<STUB>>/mobx-react_v5.1.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react' {
  declare export var observer: <Props: {}>(
    React$ComponentType<Props>
  ) => React$ComponentType<Props>;
}
